title: Luigi Gallucci
description: Microbial ecology, coding, and cooking tips
url: https://l-gallucci.github.io
baseurl: ''
theme: null
markdown: kramdown
permalink: /:title/
author:
  name: Luigi Gallucci
  email: lgallucc@mpi-bremen.de
  github: l-gallucci
  orcid: 0000-0000-0000-0000
navbar:
  - title: About
    url: /about/
  - title: Research
    url: /research/
  - title: Creative
    url: /creative/
  - title: Contact
    url: /contact/
include:
  - assets
  - _pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - vendor
